name: spark_env
channels:
  - conda-forge
dependencies:
  - python=3.10.18
  - ipykernel=6.29.5
  - pip=25.1.1
  - setuptools=80.9.0
  - wheel=0.45.1
  - tzdata
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - ipython=8.37.0
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - prompt-toolkit=3.0.51
  - pygments=2.19.1
  - traitlets=5.14.3
  - tornado=6.5.1
  - psutil=7.0.0
  - readline=8.2
  - ncurses=6.5
  - xz=5.8.1
  - zeromq=4.3.5
  - zipp=3.22.0
  - typing_extensions=4.14.0
  - packaging=25.0
  - python-dateutil=2.9.0.post0
  - six=1.17.0
  - parso=0.8.4
  - jedi=0.19.2
  - comm=0.2.2
  - executing=2.2.0
  - stack_data=0.6.3
  - pure_eval=0.2.3
  - asttokens=3.0.0
  - wcwidth=0.2.13
  - decorator=5.2.1
  - platformdirs=4.3.8
  - exceptiongroup=1.3.0
  - libffi=3.4.6
  - libexpat=2.7.0
  - libzlib=1.3.1
  - libsqlite=3.50.0
  - openssl=3.5.0
  - ca-certificates=2025.4.26
  - pip:
      - mlflow
      - duckdb
      - pandas
      - pyarrow
      - scikit-learn
      - xgboost
      - tqdm
